### ISSUE TITLE
Upgrade to Django 1.11 or 2.0?

### ISSUE THREAD

**Issue by lggwettmann** [arneb/django-messages#103]
Any chance this package will be updated to work with Django 1.11 or 2.0? 

I get a 
```Reverse for 'messages_inbox' not found. 'messages_inbox' is not a valid view function or pattern name.```
after the update to Django 1.11.

**Comment by arneb** [comment]
Yes, there's a chance ... There even is a Pull Request open, where I commented what needs to be changed, but the opener never updated it:

https://github.com/arneb/django-messages/pull/102

If you want to fix the PR, I will merge it.

My time is currently very limited, so I cannot do everything alone, sorry!

**Comment by brandon-clair** [comment]
I've done the minimum updates to run with Django 2.0+ in PR #105. They are the same changes as imdiegoestevez made in PR #102, minus the things they have not corrected.

**Comment by arneb** [comment]
should be fixed in 0.6.0
