### ISSUE TITLE
prevent sending messages to inactive users

### ISSUE THREAD

**Issue by frankystone** [arneb/django-messages#118]
As the django documentation prefer setting a users is_active flag to False instead of deletion, django-messages should also prevent sending messages to users who's is_active flag is set to False.

**Comment by arneb** [comment]
good idea

**Comment by arneb** [comment]
This can be solved with a recipient_filter (```lambda u: u.is_active```) as parameter to the compose view in url-conf. 

I'm adding it to the test-suite as an example.

**Comment by frankystone** [comment]
I think sending to users who's is_active flag is set to false should be default, not optional.

Anyway thanks for your work :-)
