### ISSUE TITLE
TypeError at /messages/compose/: render() got an unexpected keyword argument 'renderer'

### ISSUE THREAD

**Issue by vonmaster** [arneb/django-messages#130]
Hi,

First, thank you for this incredible library. I have installed the latest version of Django Messages and I am seeing this error when I load the Compose Page:
```
TypeError at /messages/compose/
render() got an unexpected keyword argument 'renderer'
```
I am using Django 2.2.3 and, after some searches, I found out that this error is due to this backwards-incompatible change in Django 2.1: `Support for Widget.render() methods without the renderer argument is removed.`

The culprit is located in `django-messages/django_messages/fields.py`:
```
class CommaSeparatedUserInput(widgets.Input):
    input_type = 'text'

    def render(self, name, value, attrs=None):
        if value is None:
            value = ''
        elif isinstance(value, (list, tuple)):
            value = (', '.join([getattr(user, get_username_field()) for user in value]))
        return super(CommaSeparatedUserInput, self).render(name, value, attrs)

```

The fix that I found was to change the method signature of render, so that it looks like this:
 `def render(self, name, value, attrs=None, renderer=None):`

Would it be possible to make the rectification please?

Thank you in advance,

**Comment by arneb** [comment]
thank you for the report, I will take a look into this

**Comment by arneb** [comment]
@vonmaster I've pushed a change which should fix the problem. Please test in your environment and re-open the issue, if the problem still exists.
