### ISSUE TITLE
TypeError: 'bool' object is not callable request.user.is_authenticated()

### ISSUE THREAD

**Issue by vonmaster** [arneb/django-messages#132]
Hi,

I stumbled upon a small issue. 

In `context_processors.py`, `request.user.is_authenticated()` should be replaced by `request.user.is_authenticated`.

In older versions of Django, request.user.is_authenticated was a method. It is now an attribute  ([source](https://docs.djangoproject.com/en/1.11/ref/contrib/auth/#django.contrib.auth.models.User.is_authenticated)).

For reference, here is the complete correct code:
```
from django_messages.models import inbox_count_for

def inbox(request):
    if request.user.is_authenticated:
        return {'messages_inbox_count': inbox_count_for(request.user)}
    else:
        return {}
```

Regards,

**Comment by arneb** [comment]
This was already fixed in https://github.com/arneb/django-messages/commit/f391b119b74eebe34a8dfb089e7ced14d96cfcff 3 days ago.

A new release including this change will be made available shortly. Please use master branch instead, if it's urgent
