### ISSUE TITLE
Support for Django-Ckeditor

### ISSUE THREAD

**Issue by samson256** [arneb/django-messages#144]
I know this is possible, is it possible to add support for django ckeditor so that, the editor can be reach in message being typed?

```
from ckeditor_uploader.fields import RichTextUploadingField
body = RichTextUploadingField()
```

**Comment by arneb** [comment]
Sure!
Add the field by using your own form class: https://django-messages.readthedocs.io/en/latest/customizing.html#modifying-form-classes

If that's not enough also override the template with your own.
