### ISSUE TITLE
Missing translations

### ISSUE THREAD

**Issue by qcaron** [arneb/django-messages#46]
Hi !

I noticed that there are missing translations for "No messages." at least in French and Spanish. I can make the update for French!

Cheers,
Quentin

**Comment by qcaron** [comment]
So the French update has been pushed ;) 
There still is work to do for other languages such as Spanish.

**Comment by arneb** [comment]
Sorry, I don't speak spanish, so I can't provide the translation, maybe someone else can contribute it ...
