### ISSUE TITLE
Mail templates location

### ISSUE THREAD

**Issue by qcaron** [arneb/django-messages#50]
Hi guys,

I have been desperately looking for the email notification templates such as *templates/messages/new_message.html* as found in translation files. For example:

```po
#: templates/messages/new_message.html:1
#, python-format
msgid ""
"Hello %(recipient)s,\n"
"\n"
"you received a private message from %(sender)s with\n"
"the following contents:"
msgstr ""
"Bonjour %(recipient)s,\n"
"\n"
"vous avez reçu un message privé de %(sender)s avec\n"
"le contenu suivant :"
```

I would like to customize the sender here so I need to override the default template.

Thanks for your help !

Cheers,
Quentin

**Comment by arneb** [comment]
templates were moves from "messages" folder to "django_messages" folder some time ago. here's the new_message.html template:

https://github.com/arneb/django-messages/blob/master/django_messages/templates/django_messages/new_message.html

**Comment by qcaron** [comment]
How did I missed it?... Thanks Arne !
