### ISSUE TITLE
Python 3

### ISSUE THREAD

**Issue by vhf** [arneb/django-messages#51]
Any plans on supporting Python 3 for this package?

**Comment by arneb** [comment]
yes, it is planned, please see: https://github.com/arneb/django-messages/issues/23

maybe you can provide some feedback, what else is needed?

**Comment by vhf** [comment]
Thanks a lot for your quick answer.

I'm developing a py3 Django app using the git master version of this app, and it works so far. I'll keep you posted if and issues PR on #23 if I see any more work to be done.

In the mean time, everything seems to work nicely on master.

**Comment by arneb** [comment]
thank you for the quick feedback!
