### ISSUE TITLE
Modifying templates names Django 1.8

### ISSUE THREAD

**Issue by qasimalbaqali** [arneb/django-messages#57]
Trying to modify the template for inbox using 
```
url(r'^inbox/$',
    inbox,
    {'template_name': 'my_inbox.html',},
    name='messages_inbox'),
```

I get 
```Exception Value: name 'inbox' is not defined```

edit: turns out I just needed to import ```from django_messages.views import inbox```, but that didn't fix anything. I still go to /messages/inbox/ and the template that is being rendered is the default one.

**Comment by arneb** [comment]
is the directory with "my_inbox.html" listed in the DIRS configuration of the TEMPLATE Backend?

**Comment by qasimalbaqali** [comment]
Yup, that was my problem. I already went and edited the templates that were in the packages. Thank you.
