### ISSUE TITLE
Django-messages messages_inbox_count template tag not working as expected

### ISSUE THREAD

**Issue by mtaiyi** [arneb/django-messages#59]
1.pip install django-messages
2.added 'messages', to INSTALLED_APPS
3.added django-messages 'messages.context_processors.inbox', context processor to 
TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'templates')]
        ,
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                'django_messages.context_processors.inbox',
            ],
        },
    },
]

Finally i am trying to use messages_inbox_count tag inside one of my template as follows:

<a href="/messages/inbox/">Inbox ({{ messages_inbox_count }})</a>

However, as expected this doesn't show up any inbox count on the page.

**Comment by arneb** [comment]
try:
```
{% load inbox %}
{% inbox_count %}
```
It's not called messages_inbox_count, just inbox_count.

If it still does not work, please try installing from the git repo instead if pypi (a new release will be uploaded in the next weeks).
