### ISSUE TITLE
Backend admin - Not Popups windows for look sender,received and parent msg in backend

### ISSUE THREAD

**Issue by manbago** [arneb/django-messages#60]
I had two similar proyects. One for development and one for producctión.

In Development:
When i add a msg i pulse over magnifying glass icon I get de popups windows and run ok to selec sender, receiver and parent msg. (The URL of icon is ../admin/auth/user/?t=id)

In Production:
When i add a msg i pulse over magnifying glass icon I do not get de popups windows, the system go to  user list and not back to message window. It is strange, the URL changed (The URL of icon is .../auth/user/?_to_field=id).

best regards

**Comment by arneb** [comment]
sound like you are using different django versions for development and production
