### ISSUE TITLE
how to write  form's ```recipienet``` field when I want to custom compose template?

### ISSUE THREAD

**Issue by viciousstar** [arneb/django-messages#63]
I use django1.8 in python3.4.
I want to custom my own compose template.Here is my code:
```
<input id="id_recipient" class="form-control" name="recipient" type="text" value="{{form.recipient.value}}">
```
When I driectly reply a message,it will fill the value with a list of `User Class`.
![qq 20151219204450](https://cloud.githubusercontent.com/assets/7370577/11913027/a1ac147e-a691-11e5-95f1-a55b0c019cfc.jpg).
Help! Are there some methods that I do not need modify the source code can solve my problem.Thanks.

**Comment by arneb** [comment]
please update to the latest commit in the master branch. this should fix your problem.
