### ISSUE TITLE
'url' is not a valid tag or filter in tag library 'future'

### ISSUE THREAD

**Issue by gladsonvm** [arneb/django-messages#71]
This issue is noticed in django 1.9. It can be resolved by template overriding. I think it will be better if the {% load url from future %} is removed from templates.

**Comment by dsalaj** [comment]
I have created a pull request for fixing this [here](https://github.com/arneb/django-messages/pull/73)

**Comment by pythdasch** [comment]
can't use this library till this has not be merged :(

**Comment by OscarIHS** [comment]
The same here, I just installed this library and cannot use it. 
Django 1.9.12

**Comment by arneb** [comment]
@OscarIHS please use the current master branch. It's stable and compatible with Django 1.9.

**Comment by OscarIHS** [comment]
I will, thanks.

**Comment by arneb** [comment]
fixed
