### ISSUE TITLE
About migrations

### ISSUE THREAD

**Issue by atugushev** [arneb/django-messages#72]
Why there are no any migrations? Do you plan to add them?

**Comment by arneb** [comment]
Yes, the next release (django 1.8/1.9 compatible) will have migrations.
Might take 2-3 weeks, I'm very busy right now.

**Comment by atugushev** [comment]
@arneb thanks for quick reply

**Comment by fizista** [comment]
I created patches(#75) that have migration and compatibility with Django to 1.9.

**Comment by arneb** [comment]
Migrations are now added.
