### ISSUE TITLE
When will the new version ... present contains an error in the code.

### ISSUE THREAD

**Issue by fizista** [arneb/django-messages#74]
Such an error I have:
```
  File ".../python3.4/site-packages/django_messages/templatetags/inbox.py", line 39
    raise TemplateSyntaxError, "first argument to inbox_count tag must be 'as' "
```

It is already fixed in the #30 , but in the repository PyPI, the current version 0.5.1 still contains the error.

When might be a new version in the repository PyPi?

**Comment by arneb** [comment]
Version 0.5.3 is on PyPI and contains the fix.
