### ISSUE TITLE
Django 1.10 compatability

### ISSUE THREAD

**Issue by d3cline** [arneb/django-messages#78]
I tried to run the app on Django 1.10 and it had a few issues.  Are there any plans to support this in the near future?

**Comment by arneb** [comment]
yes, of course.

**Comment by d3cline** [comment]
Awesome thanks! I will wait on adding it to my current project than. Any idea on a possible ETA? Is it being worked on already? I spent the other day fixing another package and was about to do this one when I noticed how active the community for it was, so I figured i would ask first. Thanks again!

**Comment by arneb** [comment]
feel free to work on 1.10 compatibility. 
If you provide a Pull-Request please make sure it contains only the minimal needed changes and stays compatible with at least django 1.8 and 1.9.

**Comment by Wahagn** [comment]
What issues did you have with 1.10 ? I just installed it in a webshop project I have and it works fine as far as I can tell. 

It gave one type of error but it was easy to solve. In the view.py something is used which has been taken out of Django in 1.10 so you have to change every line which has
render_to_response like this : 
replace "render_to_response" with "render" 
as first argument add "request," 
and remove this part "context_instance=RequestContext(request)"

**Comment by arneb** [comment]
the change from render_to_response to render is now committed to the master branch.
