### ISSUE TITLE
patterns has been depreciated with django 1.10

### ISSUE THREAD

**Issue by HenryMehta** [arneb/django-messages#83]
I'm setting up a new project and I'm getting the following error:

> ImportError: cannot import name patterns

This is the traceback:
```
 File "/home/henry/Documents/yusuf/env/local/lib/python2.7/site-packages/django_messages/urls.py", line 1, in <module>
    from django.conf.urls import patterns, url
```

**Comment by arneb** [comment]
Please install the current master branch directly from github, this has already been fixed.
