### ISSUE TITLE
"send xyz a message" issue

### ISSUE THREAD

**Issue by calumdf** [arneb/django-messages#93]
Hi,

Im struggling to implement the url-based approach to preloading the compose-form with the recipient-user. I understand this is the URL:
url(r'^compose/(?P<recipient>[\w.@+-]+)/$', compose, name='messages_compose_to'),
however how to i implement this into a user profile? 
Please help

**Comment by arneb** [comment]
maybe something line this:

`<a href="{% url 'messages_compose_to' user.username %}">Send {{ user.username }} a messages.</a>`
