### ISSUE TITLE
Multiples Re: after some replies

### ISSUE THREAD

**Issue by mrcmoresi** [arneb/django-messages#94]
Hi, i dont know if its a bug, but when two users send mails from the other in the same thread subjects raise the number of Re: for example

User 1 send a message to User 2 with Subject: Test Msg
User 2 reply thath message to User 1 with Subject: Re: Test Msg
User 1 reply a message to User 2 with Subject: Re: Re Test Msg
User 2 reply thath message to User 1 with Subject: Re: Re: Re: Test Msg
..

The messages in the inbox appears as differents messages and not like one thread.
there is any conflict with my project?

**Comment by arneb** [comment]
This is the current implemented behaviour: https://github.com/arneb/django-messages/blob/master/django_messages/views.py#L98 (paramter subject_template of the reply view).

I think it could be changed with little effort to use a callable to construct the subject, which get's passed the parent message. The callable could then decide, if another 'Re:' should be added or not. (just like the parameter quote_helper already works)
