### ISSUE TITLE
Ability to change database for messages

### ISSUE THREAD

**Issue by garyhlusko** [arneb/django-messages#98]
I'm looking for the ability to change the database for messages. Is there an easy configuration in the Messages Meta of models?

**Comment by arneb** [comment]
No. But you can use a DatabaseRouter to route queries for django_messages to a specific DB.

https://docs.djangoproject.com/en/1.8/topics/db/multi-db/#automatic-database-routing

Keep in mind that it will only work, if the user model is in that database too (Message has ForeignKeys to User).
